# This is our base Image
FROM python

# Creating the dir that we will host our files to

WORKDIR /app

# Copy files to dir

COPY ["." , "."]

# This how to assign the entry point for the application in order to work

CMD ["python3", "app.py"]